### ISSUE TITLE
[Roadmap] V2 plan

### ISSUE THREAD

**Issue by narumishi** [chaldea-center/chaldea#19]
The next major version v2.x is great powered by Atlas and wiki data, and brings support for web. 
Now the web app can be available at:
- https://chaldea.center
- https://cn.chaldea.center  (for China mainland)

Something in docs  https://docs.chaldea.center/v2_release.html

**Note**: 
- still in development, just for test and preview. Data may be broken between updates.
- native app(iOS/Android/Windows/etc) is not built yet because it's unstable and hard to push upgrades to clients, so just test web currently.

Before official release for V2, there are still something to do:
- for me, I need to implement the left functions such as weekly mission.
- And translation help WANTED! Each language is welcomed!
  - 5 official languages: Japanese, Simplified Chinese, Traditional Chinese, English, Korean
  - 2+ other languages: Arabic, Spanish, and others if you want to add.

For how to help with translation, check the above docs link again, also any help is welcomed! 

-------

## Abstract
- [x] Data source migration - from wikis to Atlas Academy
- [x] More Language and server support
        including all 5 official languages(JP/CN/TW/EN/KR) and other languages if anyone can help translation
- [x] Web app support

## Data Source Migration

Currently, Chaldea app mostly depends on [Mooncell](https://fgo.wiki) wiki and [Fandom](https://fategrandorder.fandom.com/wiki/Fate/Grand_Order_Wikia) wiki. These wikis do provide very detailed data and guides to FGO players. They are both based on Mediawiki framework, which is more human-friendly, but less program-friendly. With more and more rich wiki contents, it becomes more difficult to parse structured data for Chaldea app. Meanwhile, more bugs and exceptions are raised.

Finally, I decided to migrate the main data source to [Atlas Academy](https://atlasacademy.io/atlas-academy-db/). Atlas provides original parsed game data of all servers. It makes easier to maintain dataset, but note that it maybe be less human-readable for some contents.  Of course, the wikis are still used to provide those data not in game db. 

## More Language/Server Support

As said above, the app is mostly based on Chinese wiki and actually it's designed for Chinese users at the beginning. 
Thanks to the ability of Atlas Database, more server support will be much easier. 

However,

### Translation needed!!!

**What need to be translated**
1. unreleased contents in non-JP server 
2. UI text

**What languages**
I only play FGO CN and JP server, and know little about Japanese. So any translation other than Chinese is welcomed!
1. Japanese 日本語 
2. Chinese(Simplified) - we have Mooncell data
3. Chinese(Traditional) - 如果需要更地道的繁中的话
4. English
5. Korean
6. Other languages like Spanish

If you are willing to help with translations(for long term I hope), please [contact me](https://docs.chaldea.center/feedback.html). 
Discord is preferred: [https://discord.gg/5M6w5faqjP](https://discord.gg/5M6w5faqjP)

## Web app support

If you don't want to install an application on your device, you can try the web app(PWA). 

Not all features are supported on web yet. 

---------

## Features will be dropped
... not counted

## Testing
If you want to test it then, please join the [Discord](https://discord.gg/5M6w5faqjP) to get more info.

**Comment by narumishi** [comment]
## Known Issues

- https://github.com/flutter/flutter/issues/84833
